---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

transport:
  ssh_key:  'C:\\Users\\Iman Kurniawan\\.vagrant.d\\insecure_private_key'

verifier:
  name: inspec

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[elasticsearch::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
